version: "3.9"

services:
  api: &api
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: prunedge/mpicapture-api
    command: python manage.py runserver 0.0.0.0:12000
    volumes:
      - ./app:/app
    ports:
      - "12000:12000"
    env_file:
      - ./.env
    restart: always

  redis:
    image: bitnami/redis
    ports:
      - "16739:6739"
    env_file:
      - ./.env

  celery:
    <<: *api
    command: celery -A core worker --loglevel=info --logfile=logs/celery.log
    ports: [ ]
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - api

  celery-beat:
    <<: *api
    command: celery -A core beat -l info
    ports: [ ]
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - celery

  dashboard:
    <<: *api
    command: celery --broker=${REDIS_URL} flower --port=5555
    ports:
      - "5559:5555"
    env_file:
      - ./.env
    depends_on:
      - api
      - celery
      - redis