version: "3.9"

services:
  api: &api
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: prunedge/hrpay-api
    command: python manage.py runserver 0.0.0.0:10007
    volumes:
      - ./app:/app
    ports:
      - "10009:10009"
    env_file:
      - ./.env
    restart: unless-stopped

  celery:
    <<: *api
    command: celery -A core worker --loglevel=info --logfile=logs/celery.log
    ports: [ ]
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - api

  celery-beat:
    <<: *api
    command: celery -A core beat -l info
    ports: [ ]
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - celery

  dashboard:
    <<: *api
    command: celery --broker=${REDIS_URL} flower --port=5555
    ports:
      - "5559:5555"
    env_file:
      - ./.env
    depends_on:
      - api
      - celery

  locust-master:
    image: locustio/locust
    ports:
      - "9089:8089"
    volumes:
      - ./app:/app
    command: -f /app/locustfile.py --master -H http://localhost:8000
    depends_on:
      - api

  locust-worker:
    image: locustio/locust
    volumes:
      - ./app:/app/
    command: -f /app/locustfile.py --worker --master-host locust-master
    depends_on:
      - api